### ISSUE TITLE
? Useable with variables, not files?

### ISSUE THREAD

**Issue by GaiaGrower** [ikergarcia1996/Easy-Translate#11]
Hello,
I have a great many headlines and articles, most not in English, stored in a database, which I can store in python lists.
I would like to loop through the lists, and translate each variable, without writing the contents to a file first.
This is part of a website, which displays a great many headlines, to start, for the users to choose from.
Writing each headline to a file, translate, and read the file back to a list will take too much time.
Thank you, in advance, for your help.
Baruch

**Comment by ikergarcia1996** [comment]
Hi @GaiaGrower 

We currently don't support this behavior.  But it should be very easy to modify the `translate.py` script for this use case.
